from django.urls import path
from billing.views import (
    CreatePurchaseOrderView,
    MerchantPurchaseOrderListView,
    MerchantPODetailView,
    VendorPODetailView,
    VendorPurchaseOrderListView,
    ApprovePOView,
    ShipProductView,
    MarkProductDeliveredView,
    RaiseInvoiceView,
    MerchantInvoiceDetailView,
    MerchantInvoiceListView,
    InvoicePaymentView,
    VendorInvoiceDetailView,
    VendorInvoiceListView,
)

urlpatterns = [
    path(
        "create_purchase_order/<int:order_item_id>/",
        CreatePurchaseOrderView.as_view(),
        name="create_purchase_order",
    ),
    path(
        "merchant_purchase_order_list/",
        MerchantPurchaseOrderListView.as_view(),
        name="merchant_purchase_order_list",
    ),
    path(
        "merchant_po_detail/<int:po_id>/",
        MerchantPODetailView.as_view(),
        name="merchant_po_detail",
    ),
    path(
        "merchant_invoice_list/",
        MerchantInvoiceListView.as_view(),
        name="merchant_invoice_list",
    ),
    path(
        "make_invoice_payment/<int:invoice_id>/",
        InvoicePaymentView.as_view(),
        name="make_invoice_payment",
    ),
    path(
        "merchant_invoice_detail/<int:invoice_id>/",
        MerchantInvoiceDetailView.as_view(),
        name="merchant_invoice_detail",
    ),
    path(
        "vendor_purchase_order_list/",
        VendorPurchaseOrderListView.as_view(),
        name="vendor_purchase_order_list",
    ),
    path(
        "vendor_po_detail/<int:po_id>/",
        VendorPODetailView.as_view(),
        name="vendor_po_detail",
    ),
    path(
        "approve_purchase_order/<int:po_id>/",
        ApprovePOView.as_view(),
        name="approve_purchase_order",
    ),
    path(
        "update_arrival_date/<int:po_id>/",
        ShipProductView.as_view(),
        name="update_arrival_date",
    ),
    path(
        "mark_delivered/<int:po_id>/",
        MarkProductDeliveredView.as_view(),
        name="mark_delivered",
    ),
    path(
        "raise_invoice/<int:po_id>/",
        RaiseInvoiceView.as_view(),
        name="raise_invoice",
    ),
    path(
        "vendor_invoice_list/",
        VendorInvoiceListView.as_view(),
        name="vendor_invoice_list",
    ),
    path(
        "vendor_invoice_detail/<int:invoice_id>/",
        VendorInvoiceDetailView.as_view(),
        name="vendor_invoice_detail",
    ),
]
